name: Push to Avrae
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pull:
    uses: Dintanthrir/avrae-autoupdate/.github/workflows/push_to_avrae.yaml@main
    secrets: inherit