name: "Avrae Auto-Update"
description: "Updates snippets and aliases within Avrae Collections"
branding:
  color: "blue"
  icon: "upload-cloud"

inputs:
  collection-ids-file:
    description: "File path that contains collection IDs. See README.md and example repo."
    required: true
    default: "collection-ids.json"
  avrae-token:
    description: "Your Avrae API token"
    required: true
  modified-files:
    description: "JSON list of modified files"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
