name: "Avrae Auto-Update"
description: "Updates snippets and aliases within Avrae Collections"
branding:
  color: "blue"
  icon: "upload-cloud"

inputs:
  collections_id_file_name:
    description: "File path that contains collection IDs. See README.md and example repo."
    required: true
    default: "collections.json"
  gvars_id_file_name:
    description: "File path that contains GVAR IDs."
    required: true
    default: "gvars.json"
  avrae_token:
    description: "Your Avrae API token"
    required: true
  modified_files:
    description: "JSON list of modified files"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
