name: Update Avrae Collections
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: modified-files
        uses: jitterbit/get-changed-files@master
        with:
          format: "json"
      - uses: 1drturtle/avrae-autoupdate@main
        with:
          avrae_token: "${{ secrets.AVRAE_TOKEN }}"
          collections_id_file_name: "collections.json"
          gvars_id_file_name: "gvars.json"
          modified_files: "${{ steps.modified-files.outputs.added_modified }}"
