name: Push changes to Avrae

on:
  workflow_call:
    inputs:
      collections:
        description: Relative path to a JSON file containing a JSON object mapping Avrae collection ids to relative directory paths in the repo.
        default: collections.json
        required: false
        type: string
      gvars:
        description: Relative path to a JSON file containing a JSON object mapping Avrae gvar keys to relative file paths in the repo.
        default: gvars.json
        required: false
        type: string
    secrets:
      avrae_token:
        description: An authentication token from https://avrae.io/dashboard
        required: true

jobs:
  deploy_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Dintanthrir/avrae-autoupdate/actions/push@main
        with:
          collections: ${{ inputs.collections }}
          gvars: ${{ inputs.gvars }}
          avrae_token: ${{ secrets.avrae_token }}
